// For development and debugging purposes only.
// All defines should be disabled for production builds.

{.$DEFINE MM_BUCKETMM}
{.$DEFINE MM_BUCKETMM_ASM}
{.$DEFINE MM_DKCIA32MM}
{.$DEFINE MM_EWCMM}
{.$DEFINE MM_FASTMM2}
{.$DEFINE MM_FASTMM3}
{.$DEFINE MM_FASTMM4}
{.$DEFINE MM_FASTMM4_16}
{.$DEFINE MM_MULTIMM}
{.$DEFINE MM_NEXUSMM}
{.$DEFINE MM_QMEMORY}
{.$DEFINE MM_RECYCLERMM}
{.$DEFINE MM_RTLMM}
{.$DEFINE MM_TOPMM}
{.$DEFINE MM_WINMEM}

//{.$DEFINE MM_PSDMM}        // disabled...deprecated
//{.$DEFINE MM_LOCALHEAP}    // disabled... identical to WINMEM
//{.$DEFINE MM_HEAPMM}       // disabled... identical to WINMEM


