@echo off
SETLOCAL ENABLEDELAYEDEXPANSION

@".\Sr32.EXE" /i /s"diocp.coder.baseObject" /r"diocp_coder_baseObject"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.coder.tcpClient" /r"diocp_coder_tcpClient"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.coder.tcpServer" /r"diocp_coder_tcpServer"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.core.engine" /r"diocp_core_engine"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.core.rawPosixSocket" /r"diocp_core_rawPosixSocket"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.core.rawWinSocket" /r"diocp_core_rawWinSocket"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.ex.httpServer" /r"diocp_ex_httpServer"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.ex.ntrip" /r"diocp_ex_ntrip"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.ex.server" /r"diocp_ex_server"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.res" /r"diocp_res"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.sockets.utils" /r"diocp_sockets_utils"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.sockets" /r"diocp_sockets"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp_sockets.utils" /r"diocp_sockets_utils"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.task" /r"diocp_task"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.tcp.blockClient" /r"diocp_tcp_blockClient"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.tcp.client" /r"diocp_tcp_client"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.tcp.server" /r"diocp_tcp_server"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.udp" /r"diocp_udp"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.vclreg" /r"diocp_vclreg"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.winapi.Qos" /r"diocp_winapi_Qos"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"diocp.winapi.winsock2" /r"diocp_winapi_winsock2"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"utils.buffer" /r"utils_buffer"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"utils.bufferTools" /r"utils_bufferTools"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"utils.byteTools" /r"utils_byteTools"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"utils.hashs" /r"utils_hashs"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"utils.locker" /r"utils_locker"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"utils.objectPool" /r"utils_objectPool"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"utils.queues" /r"utils_queues"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"utils.safeLogger" /r"utils_safeLogger"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"utils.strings" /r"utils_strings"	 /d /p*.pas /n /u /q
@".\Sr32.EXE" /i /s"utils.zipTools" /r"utils_zipTools"	 /d /p*.pas /n /u /q


@".\Sr32.EXE" /i /s"diocp.coder.baseObject" /r"diocp_coder_baseObject"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.coder.tcpClient" /r"diocp_coder_tcpClient"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.coder.tcpServer" /r"diocp_coder_tcpServer"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.core.engine" /r"diocp_core_engine"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.core.rawPosixSocket" /r"diocp_core_rawPosixSocket"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.core.rawWinSocket" /r"diocp_core_rawWinSocket"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.ex.httpServer" /r"diocp_ex_httpServer"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.ex.ntrip" /r"diocp_ex_ntrip"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.ex.server" /r"diocp_ex_server"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.res" /r"diocp_res"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.sockets.utils" /r"diocp_sockets_utils"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.sockets" /r"diocp_sockets"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.task" /r"diocp_task"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.tcp.blockClient" /r"diocp_tcp_blockClient"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.tcp.client" /r"diocp_tcp_client"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.tcp.server" /r"diocp_tcp_server"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.udp" /r"diocp_udp"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.vclreg" /r"diocp_vclreg"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.winapi.Qos" /r"diocp_winapi_Qos"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"diocp.winapi.winsock2" /r"diocp_winapi_winsock2"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"utils.buffer" /r"utils_buffer"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"utils.bufferTools" /r"utils_bufferTools"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"utils.byteTools" /r"utils_byteTools"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"utils.hashs" /r"utils_hashs"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"utils.locker" /r"utils_locker"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"utils.objectPool" /r"utils_objectPool"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"utils.queues" /r"utils_queues"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"utils.safeLogger" /r"utils_safeLogger"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"utils.strings" /r"utils_strings"	 /d /p*.dpr /n /u /q
@".\Sr32.EXE" /i /s"utils.zipTools" /r"utils_zipTools"	 /d /p*.dpr /n /u /q


@".\Sr32.EXE" /i /s"diocp.coder.baseObject" /r"diocp_coder_baseObject"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.coder.tcpClient" /r"diocp_coder_tcpClient"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.coder.tcpServer" /r"diocp_coder_tcpServer"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.core.engine" /r"diocp_core_engine"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.core.rawPosixSocket" /r"diocp_core_rawPosixSocket"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.core.rawWinSocket" /r"diocp_core_rawWinSocket"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.ex.httpServer" /r"diocp_ex_httpServer"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.ex.ntrip" /r"diocp_ex_ntrip"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.ex.server" /r"diocp_ex_server"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.res" /r"diocp_res"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.sockets.utils" /r"diocp_sockets_utils"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.sockets" /r"diocp_sockets"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.task" /r"diocp_task"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.tcp.blockClient" /r"diocp_tcp_blockClient"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.tcp.client" /r"diocp_tcp_client"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.tcp.server" /r"diocp_tcp_server"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.udp" /r"diocp_udp"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.vclreg" /r"diocp_vclreg"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.winapi.Qos" /r"diocp_winapi_Qos"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"diocp.winapi.winsock2" /r"diocp_winapi_winsock2"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"utils.buffer" /r"utils_buffer"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"utils.bufferTools" /r"utils_bufferTools"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"utils.byteTools" /r"utils_byteTools"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"utils.hashs" /r"utils_hashs"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"utils.locker" /r"utils_locker"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"utils.objectPool" /r"utils_objectPool"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"utils.queues" /r"utils_queues"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"utils.safeLogger" /r"utils_safeLogger"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"utils.strings" /r"utils_strings"	 /d /p*.dpk /n /u /q
@".\Sr32.EXE" /i /s"utils.zipTools" /r"utils_zipTools"	 /d /p*.dpk /n /u /q
