cd source
ren	diocp.coder.baseObject.pas	diocp_coder_baseObject.pas
ren	diocp.coder.tcpClient.pas	diocp_coder_tcpClient.pas
ren	diocp.coder.tcpServer.pas	diocp_coder_tcpServer.pas
ren	diocp.core.engine.pas	diocp_core_engine.pas
ren	diocp.core.rawPosixSocket.pas	diocp_core_rawPosixSocket.pas
ren	diocp.core.rawWinSocket.pas	diocp_core_rawWinSocket.pas
ren	diocp.ex.httpServer.pas	diocp_ex_httpServer.pas
ren	diocp.ex.ntrip.pas	diocp_ex_ntrip.pas
ren	diocp.ex.server.pas	diocp_ex_server.pas
ren	diocp.res.pas	diocp_res.pas
ren	diocp.sockets.pas	diocp_sockets.pas
ren	diocp.sockets.utils.pas	diocp_sockets_utils.pas
ren	diocp.task.pas	diocp_task.pas
ren	diocp.tcp.blockClient.pas	diocp_tcp_blockClient.pas
ren	diocp.tcp.client.pas	diocp_tcp_client.pas
ren	diocp.tcp.server.pas	diocp_tcp_server.pas
ren	diocp.udp.pas	diocp_udp.pas
ren	diocp.vclreg.pas	diocp_vclreg.pas
ren	diocp.winapi.Qos.pas	diocp_winapi_Qos.pas
ren	diocp.winapi.winsock2.pas	diocp_winapi_winsock2.pas
ren	utils.buffer.pas	utils_buffer.pas
ren	utils.bufferTools.pas	utils_bufferTools.pas
ren	utils.byteTools.pas	utils_byteTools.pas
ren	utils.hashs.pas	utils_hashs.pas
ren	utils.locker.pas	utils_locker.pas
ren	utils.objectPool.pas	utils_objectPool.pas
ren	utils.queues.pas	utils_queues.pas
ren	utils.safeLogger.pas	utils_safeLogger.pas
ren	utils.strings.pas	utils_strings.pas
ren	utils.zipTools.pas	utils_zipTools.pas
